import { NextResponse } from "next/server"
import { jsPDF } from "jspdf"

import { getGuarantorReferenceConsentContext, recordGuarantorReferenceDecision } from "@/lib/server/applications"
import { sendGuarantorDeclarationCopyNotification } from "@/lib/server/notifications"
import { consumeAuthChallenge } from "@/lib/server/auth-security"

type DeclarationContext = {
  applicationId: string
  applicantName: string
  applicantEmail: string
  propertyAddress: string
  refereeName: string
  refereeEmail: string
  requestedByEmail: string
  requestedAt: string
  requestStatus: string
  respondedAt: string | null
  expiresAt: string | null
}

function formatDate(value?: string | null) {
  if (!value) {
    return "Not recorded"
  }

  const parsed = Date.parse(value)
  if (!Number.isFinite(parsed)) {
    return value
  }

  return new Date(parsed).toLocaleString("en-GB")
}

function buildGuarantorDeclarationPdf(context: DeclarationContext) {
  const pdf = new jsPDF({
    unit: "pt",
    format: "a4",
  })

  const left = 48
  const right = 547
  const lineGap = 16
  let y = 54

  const writeLine = (text: string, options?: { bold?: boolean; gap?: number }) => {
    pdf.setFont("helvetica", options?.bold ? "bold" : "normal")
    const lines = pdf.splitTextToSize(text, right - left)
    for (const line of lines) {
      pdf.text(String(line), left, y)
      y += lineGap
    }
    y += options?.gap ?? 0
  }

  writeLine("Guarantor Responsibility Declaration", { bold: true, gap: 6 })
  writeLine("This copy is generated for records and court evidence where required.", { gap: 12 })

  writeLine(`Application ID: ${context.applicationId}`)
  writeLine(`Property: ${context.propertyAddress}`)
  writeLine(`Applicant: ${context.applicantName} (${context.applicantEmail})`)
  writeLine(`Guarantor Contact: ${context.refereeName}${context.refereeEmail ? ` (${context.refereeEmail})` : ""}`)
  writeLine(`Request Issued By: ${context.requestedByEmail}`)
  writeLine(`Request Issued At: ${formatDate(context.requestedAt)}`)
  writeLine(`Link Expiry: ${formatDate(context.expiresAt)}`, { gap: 10 })

  writeLine("Legal Declaration and Acknowledgement", { bold: true, gap: 4 })
  writeLine(
    "1. The guarantor acknowledges that, upon acceptance, they may be required to execute or be treated as having accepted the substance of a Guarantee and Indemnity in support of the tenancy obligations of the applicant.",
  )
  writeLine(
    "2. The guarantor acknowledges that liability may be joint and several and may extend to rent, mesne profits, interest, damages, costs, losses, and other sums lawfully due under or in connection with the tenancy.",
  )
  writeLine(
    "3. The guarantor acknowledges that liability may continue for the contractual term and any statutory continuation, renewal, variation, or periodic continuation of the tenancy where enforceable in law.",
  )
  writeLine(
    "4. The guarantor acknowledges that the landlord or authorised agent may proceed directly against the guarantor without first enforcing remedies against the tenant where permitted by contract or law.",
  )
  writeLine(
    "5. The guarantor confirms that they have had adequate opportunity to seek independent legal advice and that they understand the nature and extent of the obligations before responding.",
  )
  writeLine(
    "6. The guarantor confirms that the response is provided freely, voluntarily, and with full capacity, and that they are financially able to satisfy the obligations they are agreeing to assume.",
    {
      gap: 10,
    },
  )
  writeLine(
    "Important: This declaration is provided for acknowledgement and evidential purposes and does not limit any fuller rights, remedies, or obligations contained in the final tenancy documentation.",
    {
      gap: 10,
    },
  )

  writeLine(`Recorded Response: ${context.requestStatus.replaceAll("_", " ")}`)
  writeLine(`Response Recorded At: ${formatDate(context.respondedAt)}`)
  writeLine(`Generated by RentSimple on ${formatDate(new Date().toISOString())}`)

  return Buffer.from(pdf.output("arraybuffer"))
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const token = searchParams.get("token")?.trim()

  if (!token) {
    return NextResponse.json({ error: "Consent token is required." }, { status: 400 })
  }

  const result = await getGuarantorReferenceConsentContext(token)

  if (result.error === "InvalidToken") {
    return NextResponse.json({ error: "This guarantor link is invalid." }, { status: 400 })
  }

  if (result.error === "ApplicationNotFound" || result.error === "RequestNotFound") {
    return NextResponse.json({ error: "This guarantor request is no longer available." }, { status: 404 })
  }

  if (result.error || !result.context) {
    return NextResponse.json({ error: "Unable to load guarantor details." }, { status: 500 })
  }

  return NextResponse.json({ context: result.context })
}

export async function POST(request: Request) {
  const body = (await request.json().catch(() => null)) as
    | {
        token?: string
        decision?: "agree" | "decline"
      }
    | null

  const token = body?.token?.trim()
  const decision = body?.decision === "decline" ? "decline" : "agree"

  if (!token) {
    return NextResponse.json({ error: "Consent token is required." }, { status: 400 })
  }

  const consumed = await consumeAuthChallenge("guarantor_reference", token)

  if (consumed.error || !consumed.email || !consumed.applicationId || !consumed.refereeId || !consumed.requestId) {
    return NextResponse.json({ error: "This guarantor link is invalid or has expired." }, { status: 400 })
  }

  const result = await recordGuarantorReferenceDecision({
    applicationId: consumed.applicationId,
    refereeId: consumed.refereeId,
    requestId: consumed.requestId,
    responderEmail: consumed.email,
    decision,
  })

  if (result.error === "ApplicationNotFound" || result.error === "RequestNotFound") {
    return NextResponse.json({ error: "This guarantor request is no longer available." }, { status: 404 })
  }

  if (result.error) {
    return NextResponse.json({ error: "Unable to record guarantor consent." }, { status: 500 })
  }

  const alreadyRespondedMessage =
    result.existingStatus === "declined"
      ? "Your guarantor response has already been recorded as declined."
      : "Your guarantor confirmation has already been recorded."

  const successMessage =
    decision === "decline"
      ? "Your response has been recorded. You have declined to act as guarantor."
      : "Thank you. Your guarantor confirmation has been recorded."

  if (decision === "agree" && !result.alreadyResponded && result.declarationContext?.refereeEmail) {
    try {
      const pdfBytes = buildGuarantorDeclarationPdf(result.declarationContext)

      await sendGuarantorDeclarationCopyNotification({
        toEmail: result.declarationContext.refereeEmail,
        refereeName: result.declarationContext.refereeName,
        applicantName: result.declarationContext.applicantName,
        applicantEmail: result.declarationContext.applicantEmail,
        propertyAddress: result.declarationContext.propertyAddress,
        applicationId: result.declarationContext.applicationId,
        respondedAt: result.declarationContext.respondedAt ?? new Date().toISOString(),
        declarationPdfBytes: pdfBytes,
      })
    } catch (error) {
      console.error("Unable to generate or send signed guarantor declaration copy:", error)
    }
  }

  return NextResponse.json({
    message: result.alreadyResponded ? alreadyRespondedMessage : successMessage,
    alreadyResponded: result.alreadyResponded,
  })
}
